#!/bin/bash

bt_record_execution_log() {
  local cwd="$1"
  local command="$2"
  local stdout_content="$3"
  local exit_code="$4"
  local test_dir=""
  local log_file=""
  local compact_ts=""

  if [[ -z "$cwd" || -z "$command" ]]; then
    return 0
  fi

  test_dir=$(bt_resolve_test_dir "$cwd") || return 0
  log_file=$(bt_resolve_execution_log_file "$test_dir")
  mkdir -p "$(dirname "$log_file")"

  if [[ ! -f "$log_file" ]]; then
    cat > "$log_file" <<'HEADER'
# Execution Log (auto-generated by L1 Hook)

> This file is automatically maintained by the execution-log hook.
> Do NOT edit manually. Each entry is an unforgeable record of what was actually executed.
> L2 sub-agent uses this to verify main agent's claims.

HEADER
  fi

  compact_ts=$(date +"%m-%d %H:%M:%S%z" | sed 's/\([0-9][0-9]\)\([0-9][0-9]\)$/\1/')

  cat >> "$log_file" <<ENTRY
## [$compact_ts] Bash
\`\`\`
CMD: $command
EXIT: $exit_code
\`\`\`

ENTRY

  if [[ -n "$stdout_content" && "$stdout_content" != "null" && ${#stdout_content} -gt 1 ]]; then
    {
      echo '```'
      printf '%s\n' "$stdout_content" | head -50
      if [[ $(printf '%s\n' "$stdout_content" | wc -l | tr -d ' ') -gt 50 ]]; then
        echo "... (truncated, $(printf '%s\n' "$stdout_content" | wc -l | tr -d ' ') total lines)"
      fi
      echo '```'
      echo ''
    } >> "$log_file"
  fi

  echo '---' >> "$log_file"
  echo '' >> "$log_file"
}
