#!/bin/bash
# better-test L1 Hook: Execution Log Auto-Recording
# Records every Bash command + output to .better-work/test/execution-log.md
# PostToolUse on Bash
#
# This creates an unforgeable execution record that L2 sub-agent uses
# to verify if the main agent actually executed what it claims.
set -e

INPUT=$(cat)

TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // empty')

# Only process Bash tool calls
if [[ "$TOOL_NAME" != "Bash" ]]; then
  exit 0
fi

CWD=$(echo "$INPUT" | jq -r '.cwd // empty')
COMMAND=$(echo "$INPUT" | jq -r '.tool_input.command // empty')

# Get the tool response (command output)
# PostToolUse provides tool_response with the output
RESPONSE=$(echo "$INPUT" | jq -r '.tool_response // empty')
# Try to extract stdout from response - format varies
STDOUT=$(echo "$INPUT" | jq -r '
  .tool_response.stdout //
  .tool_response.output //
  .tool_response //
  empty' 2>/dev/null | head -200)

# Skip empty commands
if [[ -z "$COMMAND" ]]; then
  exit 0
fi

# Find .better-work/test/ directory
# Strategy: CWD symlink → CWD direct → registry lookup → basename guess
LOG_DIR=""
if [[ -d "$CWD/.better-work/test" ]]; then
  LOG_DIR="$CWD/.better-work/test"
elif [[ -L "$CWD/.better-work" && -d "$(readlink "$CWD/.better-work")/test" ]]; then
  LOG_DIR="$(readlink "$CWD/.better-work")/test"
else
  # Fallback: try ~/.better-work/<dirname>/test/
  PROJECT_NAME=$(basename "$CWD")
  if [[ -d "$HOME/.better-work/$PROJECT_NAME/test" ]]; then
    LOG_DIR="$HOME/.better-work/$PROJECT_NAME/test"
  fi
fi

# If no .better-work/test/ found, skip silently
if [[ -z "$LOG_DIR" ]]; then
  exit 0
fi

# Try to find tester's run directory via session file (Phase 2: per-tester isolation)
# If session file exists, write to run directory; otherwise fallback to shared location
SESSION_DIR="$LOG_DIR/.active-sessions"
RUN_LOG_DIR=""
if [[ -d "$SESSION_DIR" ]]; then
  for PID in $PPID $(ps -o ppid= -p $PPID 2>/dev/null | tr -d ' '); do
    if [[ -f "$SESSION_DIR/$PID.json" ]]; then
      RUN_DIR_REL=$(jq -r '.run_dir // empty' < "$SESSION_DIR/$PID.json")
      if [[ -n "$RUN_DIR_REL" ]]; then
        # run_dir is relative to .better-work/test/, e.g. "history/v1.4.28/run-xxx-001-..."
        RUN_LOG_DIR="$LOG_DIR/$RUN_DIR_REL"
      fi
      break
    fi
  done
fi

if [[ -n "$RUN_LOG_DIR" && -d "$RUN_LOG_DIR" ]]; then
  LOG_FILE="$RUN_LOG_DIR/execution-log.md"
else
  # Fallback: shared location (backward compatible, used when no active session)
  LOG_FILE="$LOG_DIR/execution-log.md"
fi

# Get timestamp with timezone offset
TIMESTAMP=$(date +"%Y-%m-%dT%H:%M:%S%z" | sed 's/\([0-9][0-9]\)$/:\1/')
COMPACT_TS=$(date +"%m-%d %H:%M:%S%z" | sed 's/\([0-9][0-9]\)\([0-9][0-9]\)$/\1/')

# Create log file with header if it doesn't exist
if [[ ! -f "$LOG_FILE" ]]; then
  cat > "$LOG_FILE" << 'HEADER'
# Execution Log (auto-generated by L1 Hook)

> This file is automatically maintained by the execution-log hook.
> Do NOT edit manually. Each entry is an unforgeable record of what was actually executed.
> L2 sub-agent uses this to verify main agent's claims.

HEADER
fi

# Append entry
cat >> "$LOG_FILE" << ENTRY
## [$COMPACT_TS] Bash
\`\`\`
CMD: $COMMAND
EXIT: $(echo "$INPUT" | jq -r '.tool_response.exitCode // "?"')
\`\`\`

ENTRY

# If there's meaningful stdout, append truncated version
if [[ -n "$STDOUT" && "$STDOUT" != "null" && ${#STDOUT} -gt 1 ]]; then
  {
    echo '```'
    echo "$STDOUT" | head -50
    if [[ $(echo "$STDOUT" | wc -l) -gt 50 ]]; then
      echo "... (truncated, $(echo "$STDOUT" | wc -l) total lines)"
    fi
    echo '```'
    echo ''
  } >> "$LOG_FILE"
fi

echo '---' >> "$LOG_FILE"
echo '' >> "$LOG_FILE"

exit 0
